// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include <iostream>
#include <string>
#include <unordered_map>
#include "PhashServer.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include "Map.h"
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;
using namespace std;


class ReplicatedMap {

    private:
        unordered_map <string, string> mymap;
        int count;

    public:
        ReplicatedMap() {
            mymap = new (map <string, string>);
            count = 0;
        }

        int insert_record(key, value) {
            mymap.insert(make_pair<string, string> (key, value));
            ++count;

            if (count%5 == 0) {
                for (auto &x: mymap) {
                    cerr << "Key: " << x.first << " Value: " << x.second << endl;
                }
            }
            return 0;
        }

        string search_record(key, value) {
        }

        int delete_record(key) {
        }

        int update_record(key, value) {
        }
}

class PhashServerHandler : virtual public PhashServerIf {
    private:
        void fill_retval(ClientOpsRetval& _return, int errNo, string errMsg, string key);

        void insert_record(ClientOpsRetval& _return, cons ClientOps&w) ;

        void process_ops(ClientOpsRetval& _return, const ClientOps&w);

    public:
        PhashServerHandler() {
            // Your initialization goes here
            ReplicatedMap mymap = new(ReplicatedMap());
        }

        void ping(Ping_ACK& _return) {
            // Your implementation goes here
            printf("ping\n");
        }

        void submit_ops(ClientOpsRetval& _return, const ClientOps& ops) {
            // Your implementation goes here
            printf("submit_ops\n");
            ops.printTo(cout);
            return process_ops(_return, ops);
        }
};

void PhashServerHandler::insert_ops(ClientOpsRetval& retval, const ClientOps& ops) {

    string key = ops.key, value = ops.value, errMsg=""
    int errNo = mymap.insert_record(key, value, errMsg);

    retval.key = key;
    if (errNo != 0) {
        retval.errNo = errNo;
        retval.errMsg = errMsg;
    } else {
        retval.errMsg ="";
    }
}

void PhashServerHandler::process_ops(ClientOpsRetval& retval, const ClientOps& ops) {
    switch (w.op_type) {
        case MAP_INSERT:
            insert_ops(retval, ops);
            break;
        case MAP_DELETE:

        default:
            cerr << "Incorrect Operation";
    }
}

int main(int argc, char **argv) {
    int port = 9090;
    shared_ptr<PhashServerHandler> handler(new PhashServerHandler());
    shared_ptr<TProcessor> processor(new PhashServerProcessor(handler));
    shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
    shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
    shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

    TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
    server.serve();
    return 0;
}
