/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef wal_CONSTANTS_H
#define wal_CONSTANTS_H

#include "wal_types.h"



class walConstants {
 public:
  walConstants();

};

extern const walConstants g_wal_constants;



#endif
