/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef WALReplicator_H
#define WALReplicator_H

#include <thrift/TDispatchProcessor.h>
#include "wal_types.h"



class WALReplicatorIf {
 public:
  virtual ~WALReplicatorIf() {}
  virtual void ping(Ping_ACK& _return) = 0;
  virtual void do_ops(Ops_ACK& _return, const Ops& w) = 0;
};

class WALReplicatorIfFactory {
 public:
  typedef WALReplicatorIf Handler;

  virtual ~WALReplicatorIfFactory() {}

  virtual WALReplicatorIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(WALReplicatorIf* /* handler */) = 0;
};

class WALReplicatorIfSingletonFactory : virtual public WALReplicatorIfFactory {
 public:
  WALReplicatorIfSingletonFactory(const boost::shared_ptr<WALReplicatorIf>& iface) : iface_(iface) {}
  virtual ~WALReplicatorIfSingletonFactory() {}

  virtual WALReplicatorIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(WALReplicatorIf* /* handler */) {}

 protected:
  boost::shared_ptr<WALReplicatorIf> iface_;
};

class WALReplicatorNull : virtual public WALReplicatorIf {
 public:
  virtual ~WALReplicatorNull() {}
  void ping(Ping_ACK& /* _return */) {
    return;
  }
  void do_ops(Ops_ACK& /* _return */, const Ops& /* w */) {
    return;
  }
};


class WALReplicator_ping_args {
 public:

  WALReplicator_ping_args() {
  }

  virtual ~WALReplicator_ping_args() throw() {}


  bool operator == (const WALReplicator_ping_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const WALReplicator_ping_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const WALReplicator_ping_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class WALReplicator_ping_pargs {
 public:


  virtual ~WALReplicator_ping_pargs() throw() {}


  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _WALReplicator_ping_result__isset {
  _WALReplicator_ping_result__isset() : success(false) {}
  bool success;
} _WALReplicator_ping_result__isset;

class WALReplicator_ping_result {
 public:

  WALReplicator_ping_result() {
  }

  virtual ~WALReplicator_ping_result() throw() {}

  Ping_ACK success;

  _WALReplicator_ping_result__isset __isset;

  void __set_success(const Ping_ACK& val) {
    success = val;
  }

  bool operator == (const WALReplicator_ping_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const WALReplicator_ping_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const WALReplicator_ping_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _WALReplicator_ping_presult__isset {
  _WALReplicator_ping_presult__isset() : success(false) {}
  bool success;
} _WALReplicator_ping_presult__isset;

class WALReplicator_ping_presult {
 public:


  virtual ~WALReplicator_ping_presult() throw() {}

  Ping_ACK* success;

  _WALReplicator_ping_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _WALReplicator_do_ops_args__isset {
  _WALReplicator_do_ops_args__isset() : w(false) {}
  bool w;
} _WALReplicator_do_ops_args__isset;

class WALReplicator_do_ops_args {
 public:

  WALReplicator_do_ops_args() {
  }

  virtual ~WALReplicator_do_ops_args() throw() {}

  Ops w;

  _WALReplicator_do_ops_args__isset __isset;

  void __set_w(const Ops& val) {
    w = val;
  }

  bool operator == (const WALReplicator_do_ops_args & rhs) const
  {
    if (!(w == rhs.w))
      return false;
    return true;
  }
  bool operator != (const WALReplicator_do_ops_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const WALReplicator_do_ops_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class WALReplicator_do_ops_pargs {
 public:


  virtual ~WALReplicator_do_ops_pargs() throw() {}

  const Ops* w;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _WALReplicator_do_ops_result__isset {
  _WALReplicator_do_ops_result__isset() : success(false) {}
  bool success;
} _WALReplicator_do_ops_result__isset;

class WALReplicator_do_ops_result {
 public:

  WALReplicator_do_ops_result() {
  }

  virtual ~WALReplicator_do_ops_result() throw() {}

  Ops_ACK success;

  _WALReplicator_do_ops_result__isset __isset;

  void __set_success(const Ops_ACK& val) {
    success = val;
  }

  bool operator == (const WALReplicator_do_ops_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const WALReplicator_do_ops_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const WALReplicator_do_ops_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _WALReplicator_do_ops_presult__isset {
  _WALReplicator_do_ops_presult__isset() : success(false) {}
  bool success;
} _WALReplicator_do_ops_presult__isset;

class WALReplicator_do_ops_presult {
 public:


  virtual ~WALReplicator_do_ops_presult() throw() {}

  Ops_ACK* success;

  _WALReplicator_do_ops_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class WALReplicatorClient : virtual public WALReplicatorIf {
 public:
  WALReplicatorClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  WALReplicatorClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping(Ping_ACK& _return);
  void send_ping();
  void recv_ping(Ping_ACK& _return);
  void do_ops(Ops_ACK& _return, const Ops& w);
  void send_do_ops(const Ops& w);
  void recv_do_ops(Ops_ACK& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class WALReplicatorProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<WALReplicatorIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (WALReplicatorProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_ping(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_do_ops(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  WALReplicatorProcessor(boost::shared_ptr<WALReplicatorIf> iface) :
    iface_(iface) {
    processMap_["ping"] = &WALReplicatorProcessor::process_ping;
    processMap_["do_ops"] = &WALReplicatorProcessor::process_do_ops;
  }

  virtual ~WALReplicatorProcessor() {}
};

class WALReplicatorProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  WALReplicatorProcessorFactory(const ::boost::shared_ptr< WALReplicatorIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< WALReplicatorIfFactory > handlerFactory_;
};

class WALReplicatorMultiface : virtual public WALReplicatorIf {
 public:
  WALReplicatorMultiface(std::vector<boost::shared_ptr<WALReplicatorIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~WALReplicatorMultiface() {}
 protected:
  std::vector<boost::shared_ptr<WALReplicatorIf> > ifaces_;
  WALReplicatorMultiface() {}
  void add(boost::shared_ptr<WALReplicatorIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void ping(Ping_ACK& _return) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ping(_return);
    }
    ifaces_[i]->ping(_return);
    return;
  }

  void do_ops(Ops_ACK& _return, const Ops& w) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->do_ops(_return, w);
    }
    ifaces_[i]->do_ops(_return, w);
    return;
  }

};



#endif
