// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "WALReplicator.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

class WALReplicatorHandler : virtual public WALReplicatorIf {
 public:
  WALReplicatorHandler() {
    // Your initialization goes here
  }

  void ping(Ping_ACK& _return) {
    // Your implementation goes here
    printf("ping\n");
  }

  void do_ops(Ops_ACK& _return, const Ops& w) {
    // Your implementation goes here
    printf("do_ops\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<WALReplicatorHandler> handler(new WALReplicatorHandler());
  shared_ptr<TProcessor> processor(new WALReplicatorProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

