/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ourPackets_constants.h"



const ourPacketsConstants g_ourPackets_constants;

ourPacketsConstants::ourPacketsConstants() {
}



