/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ourPackets_CONSTANTS_H
#define ourPackets_CONSTANTS_H

#include "ourPackets_types.h"



class ourPacketsConstants {
 public:
  ourPacketsConstants();

};

extern const ourPacketsConstants g_ourPackets_constants;



#endif
