/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef PhashSlave_H
#define PhashSlave_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "wal_types.h"



#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class PhashSlaveIf {
 public:
  virtual ~PhashSlaveIf() {}
  virtual void ping(Ping_ACK& _return) = 0;
  virtual void submit_ops_to_slave(SlaveOpsAck& _return, const SlaveOps& ops) = 0;
};

class PhashSlaveIfFactory {
 public:
  typedef PhashSlaveIf Handler;

  virtual ~PhashSlaveIfFactory() {}

  virtual PhashSlaveIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(PhashSlaveIf* /* handler */) = 0;
};

class PhashSlaveIfSingletonFactory : virtual public PhashSlaveIfFactory {
 public:
  PhashSlaveIfSingletonFactory(const boost::shared_ptr<PhashSlaveIf>& iface) : iface_(iface) {}
  virtual ~PhashSlaveIfSingletonFactory() {}

  virtual PhashSlaveIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(PhashSlaveIf* /* handler */) {}

 protected:
  boost::shared_ptr<PhashSlaveIf> iface_;
};

class PhashSlaveNull : virtual public PhashSlaveIf {
 public:
  virtual ~PhashSlaveNull() {}
  void ping(Ping_ACK& /* _return */) {
    return;
  }
  void submit_ops_to_slave(SlaveOpsAck& /* _return */, const SlaveOps& /* ops */) {
    return;
  }
};


class PhashSlave_ping_args {
 public:

  PhashSlave_ping_args(const PhashSlave_ping_args&);
  PhashSlave_ping_args& operator=(const PhashSlave_ping_args&);
  PhashSlave_ping_args() {
  }

  virtual ~PhashSlave_ping_args() throw();

  bool operator == (const PhashSlave_ping_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const PhashSlave_ping_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const PhashSlave_ping_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class PhashSlave_ping_pargs {
 public:


  virtual ~PhashSlave_ping_pargs() throw();

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _PhashSlave_ping_result__isset {
  _PhashSlave_ping_result__isset() : success(false) {}
  bool success :1;
} _PhashSlave_ping_result__isset;

class PhashSlave_ping_result {
 public:

  PhashSlave_ping_result(const PhashSlave_ping_result&);
  PhashSlave_ping_result& operator=(const PhashSlave_ping_result&);
  PhashSlave_ping_result() {
  }

  virtual ~PhashSlave_ping_result() throw();
  Ping_ACK success;

  _PhashSlave_ping_result__isset __isset;

  void __set_success(const Ping_ACK& val);

  bool operator == (const PhashSlave_ping_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const PhashSlave_ping_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const PhashSlave_ping_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _PhashSlave_ping_presult__isset {
  _PhashSlave_ping_presult__isset() : success(false) {}
  bool success :1;
} _PhashSlave_ping_presult__isset;

class PhashSlave_ping_presult {
 public:


  virtual ~PhashSlave_ping_presult() throw();
  Ping_ACK* success;

  _PhashSlave_ping_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _PhashSlave_submit_ops_to_slave_args__isset {
  _PhashSlave_submit_ops_to_slave_args__isset() : ops(false) {}
  bool ops :1;
} _PhashSlave_submit_ops_to_slave_args__isset;

class PhashSlave_submit_ops_to_slave_args {
 public:

  PhashSlave_submit_ops_to_slave_args(const PhashSlave_submit_ops_to_slave_args&);
  PhashSlave_submit_ops_to_slave_args& operator=(const PhashSlave_submit_ops_to_slave_args&);
  PhashSlave_submit_ops_to_slave_args() {
  }

  virtual ~PhashSlave_submit_ops_to_slave_args() throw();
  SlaveOps ops;

  _PhashSlave_submit_ops_to_slave_args__isset __isset;

  void __set_ops(const SlaveOps& val);

  bool operator == (const PhashSlave_submit_ops_to_slave_args & rhs) const
  {
    if (!(ops == rhs.ops))
      return false;
    return true;
  }
  bool operator != (const PhashSlave_submit_ops_to_slave_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const PhashSlave_submit_ops_to_slave_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class PhashSlave_submit_ops_to_slave_pargs {
 public:


  virtual ~PhashSlave_submit_ops_to_slave_pargs() throw();
  const SlaveOps* ops;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _PhashSlave_submit_ops_to_slave_result__isset {
  _PhashSlave_submit_ops_to_slave_result__isset() : success(false) {}
  bool success :1;
} _PhashSlave_submit_ops_to_slave_result__isset;

class PhashSlave_submit_ops_to_slave_result {
 public:

  PhashSlave_submit_ops_to_slave_result(const PhashSlave_submit_ops_to_slave_result&);
  PhashSlave_submit_ops_to_slave_result& operator=(const PhashSlave_submit_ops_to_slave_result&);
  PhashSlave_submit_ops_to_slave_result() {
  }

  virtual ~PhashSlave_submit_ops_to_slave_result() throw();
  SlaveOpsAck success;

  _PhashSlave_submit_ops_to_slave_result__isset __isset;

  void __set_success(const SlaveOpsAck& val);

  bool operator == (const PhashSlave_submit_ops_to_slave_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const PhashSlave_submit_ops_to_slave_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const PhashSlave_submit_ops_to_slave_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _PhashSlave_submit_ops_to_slave_presult__isset {
  _PhashSlave_submit_ops_to_slave_presult__isset() : success(false) {}
  bool success :1;
} _PhashSlave_submit_ops_to_slave_presult__isset;

class PhashSlave_submit_ops_to_slave_presult {
 public:


  virtual ~PhashSlave_submit_ops_to_slave_presult() throw();
  SlaveOpsAck* success;

  _PhashSlave_submit_ops_to_slave_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class PhashSlaveClient : virtual public PhashSlaveIf {
 public:
  PhashSlaveClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  PhashSlaveClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping(Ping_ACK& _return);
  void send_ping();
  void recv_ping(Ping_ACK& _return);
  void submit_ops_to_slave(SlaveOpsAck& _return, const SlaveOps& ops);
  void send_submit_ops_to_slave(const SlaveOps& ops);
  void recv_submit_ops_to_slave(SlaveOpsAck& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class PhashSlaveProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<PhashSlaveIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (PhashSlaveProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_ping(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_submit_ops_to_slave(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  PhashSlaveProcessor(boost::shared_ptr<PhashSlaveIf> iface) :
    iface_(iface) {
    processMap_["ping"] = &PhashSlaveProcessor::process_ping;
    processMap_["submit_ops_to_slave"] = &PhashSlaveProcessor::process_submit_ops_to_slave;
  }

  virtual ~PhashSlaveProcessor() {}
};

class PhashSlaveProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  PhashSlaveProcessorFactory(const ::boost::shared_ptr< PhashSlaveIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< PhashSlaveIfFactory > handlerFactory_;
};

class PhashSlaveMultiface : virtual public PhashSlaveIf {
 public:
  PhashSlaveMultiface(std::vector<boost::shared_ptr<PhashSlaveIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~PhashSlaveMultiface() {}
 protected:
  std::vector<boost::shared_ptr<PhashSlaveIf> > ifaces_;
  PhashSlaveMultiface() {}
  void add(boost::shared_ptr<PhashSlaveIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void ping(Ping_ACK& _return) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ping(_return);
    }
    ifaces_[i]->ping(_return);
    return;
  }

  void submit_ops_to_slave(SlaveOpsAck& _return, const SlaveOps& ops) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->submit_ops_to_slave(_return, ops);
    }
    ifaces_[i]->submit_ops_to_slave(_return, ops);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class PhashSlaveConcurrentClient : virtual public PhashSlaveIf {
 public:
  PhashSlaveConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  PhashSlaveConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping(Ping_ACK& _return);
  int32_t send_ping();
  void recv_ping(Ping_ACK& _return, const int32_t seqid);
  void submit_ops_to_slave(SlaveOpsAck& _return, const SlaveOps& ops);
  int32_t send_submit_ops_to_slave(const SlaveOps& ops);
  void recv_submit_ops_to_slave(SlaveOpsAck& _return, const int32_t seqid);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif



#endif
