/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef wal_TYPES_H
#define wal_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>




class ClientOpsArguments;

class ClientOpsRetval;

class Ping_ACK;

class SlaveOpsArguments;

class SlaveOpsRetval;

typedef struct _ClientOpsArguments__isset {
  _ClientOpsArguments__isset() : op_type(false), key(false), value(false) {}
  bool op_type :1;
  bool key :1;
  bool value :1;
} _ClientOpsArguments__isset;

class ClientOpsArguments : public virtual ::apache::thrift::TBase {
 public:

  ClientOpsArguments(const ClientOpsArguments&);
  ClientOpsArguments& operator=(const ClientOpsArguments&);
  ClientOpsArguments() : op_type(0), key(), value() {
  }

  virtual ~ClientOpsArguments() throw();
  int16_t op_type;
  std::string key;
  std::string value;

  _ClientOpsArguments__isset __isset;

  void __set_op_type(const int16_t val);

  void __set_key(const std::string& val);

  void __set_value(const std::string& val);

  bool operator == (const ClientOpsArguments & rhs) const
  {
    if (!(op_type == rhs.op_type))
      return false;
    if (!(key == rhs.key))
      return false;
    if (!(value == rhs.value))
      return false;
    return true;
  }
  bool operator != (const ClientOpsArguments &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ClientOpsArguments & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(ClientOpsArguments &a, ClientOpsArguments &b);

inline std::ostream& operator<<(std::ostream& out, const ClientOpsArguments& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _ClientOpsRetval__isset {
  _ClientOpsRetval__isset() : errNo(false), key(false), value(false) {}
  bool errNo :1;
  bool key :1;
  bool value :1;
} _ClientOpsRetval__isset;

class ClientOpsRetval : public virtual ::apache::thrift::TBase {
 public:

  ClientOpsRetval(const ClientOpsRetval&);
  ClientOpsRetval& operator=(const ClientOpsRetval&);
  ClientOpsRetval() : errNo(0), key(), value() {
  }

  virtual ~ClientOpsRetval() throw();
  int16_t errNo;
  std::string key;
  std::string value;

  _ClientOpsRetval__isset __isset;

  void __set_errNo(const int16_t val);

  void __set_key(const std::string& val);

  void __set_value(const std::string& val);

  bool operator == (const ClientOpsRetval & rhs) const
  {
    if (!(errNo == rhs.errNo))
      return false;
    if (!(key == rhs.key))
      return false;
    if (!(value == rhs.value))
      return false;
    return true;
  }
  bool operator != (const ClientOpsRetval &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ClientOpsRetval & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(ClientOpsRetval &a, ClientOpsRetval &b);

inline std::ostream& operator<<(std::ostream& out, const ClientOpsRetval& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _Ping_ACK__isset {
  _Ping_ACK__isset() : errNo(false), errMsg(false) {}
  bool errNo :1;
  bool errMsg :1;
} _Ping_ACK__isset;

class Ping_ACK : public virtual ::apache::thrift::TBase {
 public:

  Ping_ACK(const Ping_ACK&);
  Ping_ACK& operator=(const Ping_ACK&);
  Ping_ACK() : errNo(0), errMsg() {
  }

  virtual ~Ping_ACK() throw();
  int16_t errNo;
  std::string errMsg;

  _Ping_ACK__isset __isset;

  void __set_errNo(const int16_t val);

  void __set_errMsg(const std::string& val);

  bool operator == (const Ping_ACK & rhs) const
  {
    if (!(errNo == rhs.errNo))
      return false;
    if (!(errMsg == rhs.errMsg))
      return false;
    return true;
  }
  bool operator != (const Ping_ACK &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Ping_ACK & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(Ping_ACK &a, Ping_ACK &b);

inline std::ostream& operator<<(std::ostream& out, const Ping_ACK& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _SlaveOpsArguments__isset {
  _SlaveOpsArguments__isset() : seq_num_prefix(false), seq_number(false), client_number(false), op_type(false), key(false), value(false) {}
  bool seq_num_prefix :1;
  bool seq_number :1;
  bool client_number :1;
  bool op_type :1;
  bool key :1;
  bool value :1;
} _SlaveOpsArguments__isset;

class SlaveOpsArguments : public virtual ::apache::thrift::TBase {
 public:

  SlaveOpsArguments(const SlaveOpsArguments&);
  SlaveOpsArguments& operator=(const SlaveOpsArguments&);
  SlaveOpsArguments() : seq_num_prefix(0), seq_number(0), client_number(0), op_type(0), key(), value() {
  }

  virtual ~SlaveOpsArguments() throw();
  int64_t seq_num_prefix;
  int64_t seq_number;
  int32_t client_number;
  int16_t op_type;
  std::string key;
  std::string value;

  _SlaveOpsArguments__isset __isset;

  void __set_seq_num_prefix(const int64_t val);

  void __set_seq_number(const int64_t val);

  void __set_client_number(const int32_t val);

  void __set_op_type(const int16_t val);

  void __set_key(const std::string& val);

  void __set_value(const std::string& val);

  bool operator == (const SlaveOpsArguments & rhs) const
  {
    if (!(seq_num_prefix == rhs.seq_num_prefix))
      return false;
    if (!(seq_number == rhs.seq_number))
      return false;
    if (!(client_number == rhs.client_number))
      return false;
    if (!(op_type == rhs.op_type))
      return false;
    if (!(key == rhs.key))
      return false;
    if (!(value == rhs.value))
      return false;
    return true;
  }
  bool operator != (const SlaveOpsArguments &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SlaveOpsArguments & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(SlaveOpsArguments &a, SlaveOpsArguments &b);

inline std::ostream& operator<<(std::ostream& out, const SlaveOpsArguments& obj)
{
  obj.printTo(out);
  return out;
}

typedef struct _SlaveOpsRetval__isset {
  _SlaveOpsRetval__isset() : seq_num_prefix(false), seq_number(false), client_number(false), errNo(false), errMsg(false) {}
  bool seq_num_prefix :1;
  bool seq_number :1;
  bool client_number :1;
  bool errNo :1;
  bool errMsg :1;
} _SlaveOpsRetval__isset;

class SlaveOpsRetval : public virtual ::apache::thrift::TBase {
 public:

  SlaveOpsRetval(const SlaveOpsRetval&);
  SlaveOpsRetval& operator=(const SlaveOpsRetval&);
  SlaveOpsRetval() : seq_num_prefix(0), seq_number(0), client_number(0), errNo(0), errMsg() {
  }

  virtual ~SlaveOpsRetval() throw();
  int64_t seq_num_prefix;
  int64_t seq_number;
  int32_t client_number;
  int16_t errNo;
  std::string errMsg;

  _SlaveOpsRetval__isset __isset;

  void __set_seq_num_prefix(const int64_t val);

  void __set_seq_number(const int64_t val);

  void __set_client_number(const int32_t val);

  void __set_errNo(const int16_t val);

  void __set_errMsg(const std::string& val);

  bool operator == (const SlaveOpsRetval & rhs) const
  {
    if (!(seq_num_prefix == rhs.seq_num_prefix))
      return false;
    if (!(seq_number == rhs.seq_number))
      return false;
    if (!(client_number == rhs.client_number))
      return false;
    if (!(errNo == rhs.errNo))
      return false;
    if (!(errMsg == rhs.errMsg))
      return false;
    return true;
  }
  bool operator != (const SlaveOpsRetval &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SlaveOpsRetval & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(SlaveOpsRetval &a, SlaveOpsRetval &b);

inline std::ostream& operator<<(std::ostream& out, const SlaveOpsRetval& obj)
{
  obj.printTo(out);
  return out;
}



#endif
