/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef SlaveManager_H
#define SlaveManager_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "wal_types.h"



#ifdef _WIN32
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class SlaveManagerIf {
 public:
  virtual ~SlaveManagerIf() {}
  virtual void ping(Ping_ACK& _return) = 0;
  virtual void submit_ops_to_slave(SlaveOpsRetval& _return, const SlaveOps& ops) = 0;
};

class SlaveManagerIfFactory {
 public:
  typedef SlaveManagerIf Handler;

  virtual ~SlaveManagerIfFactory() {}

  virtual SlaveManagerIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(SlaveManagerIf* /* handler */) = 0;
};

class SlaveManagerIfSingletonFactory : virtual public SlaveManagerIfFactory {
 public:
  SlaveManagerIfSingletonFactory(const boost::shared_ptr<SlaveManagerIf>& iface) : iface_(iface) {}
  virtual ~SlaveManagerIfSingletonFactory() {}

  virtual SlaveManagerIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(SlaveManagerIf* /* handler */) {}

 protected:
  boost::shared_ptr<SlaveManagerIf> iface_;
};

class SlaveManagerNull : virtual public SlaveManagerIf {
 public:
  virtual ~SlaveManagerNull() {}
  void ping(Ping_ACK& /* _return */) {
    return;
  }
  void submit_ops_to_slave(SlaveOpsRetval& /* _return */, const SlaveOps& /* ops */) {
    return;
  }
};


class SlaveManager_ping_args {
 public:

  SlaveManager_ping_args(const SlaveManager_ping_args&);
  SlaveManager_ping_args& operator=(const SlaveManager_ping_args&);
  SlaveManager_ping_args() {
  }

  virtual ~SlaveManager_ping_args() throw();

  bool operator == (const SlaveManager_ping_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const SlaveManager_ping_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SlaveManager_ping_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class SlaveManager_ping_pargs {
 public:


  virtual ~SlaveManager_ping_pargs() throw();

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _SlaveManager_ping_result__isset {
  _SlaveManager_ping_result__isset() : success(false) {}
  bool success :1;
} _SlaveManager_ping_result__isset;

class SlaveManager_ping_result {
 public:

  SlaveManager_ping_result(const SlaveManager_ping_result&);
  SlaveManager_ping_result& operator=(const SlaveManager_ping_result&);
  SlaveManager_ping_result() {
  }

  virtual ~SlaveManager_ping_result() throw();
  Ping_ACK success;

  _SlaveManager_ping_result__isset __isset;

  void __set_success(const Ping_ACK& val);

  bool operator == (const SlaveManager_ping_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const SlaveManager_ping_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SlaveManager_ping_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _SlaveManager_ping_presult__isset {
  _SlaveManager_ping_presult__isset() : success(false) {}
  bool success :1;
} _SlaveManager_ping_presult__isset;

class SlaveManager_ping_presult {
 public:


  virtual ~SlaveManager_ping_presult() throw();
  Ping_ACK* success;

  _SlaveManager_ping_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _SlaveManager_submit_ops_to_slave_args__isset {
  _SlaveManager_submit_ops_to_slave_args__isset() : ops(false) {}
  bool ops :1;
} _SlaveManager_submit_ops_to_slave_args__isset;

class SlaveManager_submit_ops_to_slave_args {
 public:

  SlaveManager_submit_ops_to_slave_args(const SlaveManager_submit_ops_to_slave_args&);
  SlaveManager_submit_ops_to_slave_args& operator=(const SlaveManager_submit_ops_to_slave_args&);
  SlaveManager_submit_ops_to_slave_args() {
  }

  virtual ~SlaveManager_submit_ops_to_slave_args() throw();
  SlaveOps ops;

  _SlaveManager_submit_ops_to_slave_args__isset __isset;

  void __set_ops(const SlaveOps& val);

  bool operator == (const SlaveManager_submit_ops_to_slave_args & rhs) const
  {
    if (!(ops == rhs.ops))
      return false;
    return true;
  }
  bool operator != (const SlaveManager_submit_ops_to_slave_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SlaveManager_submit_ops_to_slave_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class SlaveManager_submit_ops_to_slave_pargs {
 public:


  virtual ~SlaveManager_submit_ops_to_slave_pargs() throw();
  const SlaveOps* ops;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _SlaveManager_submit_ops_to_slave_result__isset {
  _SlaveManager_submit_ops_to_slave_result__isset() : success(false) {}
  bool success :1;
} _SlaveManager_submit_ops_to_slave_result__isset;

class SlaveManager_submit_ops_to_slave_result {
 public:

  SlaveManager_submit_ops_to_slave_result(const SlaveManager_submit_ops_to_slave_result&);
  SlaveManager_submit_ops_to_slave_result& operator=(const SlaveManager_submit_ops_to_slave_result&);
  SlaveManager_submit_ops_to_slave_result() {
  }

  virtual ~SlaveManager_submit_ops_to_slave_result() throw();
  SlaveOpsRetval success;

  _SlaveManager_submit_ops_to_slave_result__isset __isset;

  void __set_success(const SlaveOpsRetval& val);

  bool operator == (const SlaveManager_submit_ops_to_slave_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const SlaveManager_submit_ops_to_slave_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const SlaveManager_submit_ops_to_slave_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _SlaveManager_submit_ops_to_slave_presult__isset {
  _SlaveManager_submit_ops_to_slave_presult__isset() : success(false) {}
  bool success :1;
} _SlaveManager_submit_ops_to_slave_presult__isset;

class SlaveManager_submit_ops_to_slave_presult {
 public:


  virtual ~SlaveManager_submit_ops_to_slave_presult() throw();
  SlaveOpsRetval* success;

  _SlaveManager_submit_ops_to_slave_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class SlaveManagerClient : virtual public SlaveManagerIf {
 public:
  SlaveManagerClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  SlaveManagerClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping(Ping_ACK& _return);
  void send_ping();
  void recv_ping(Ping_ACK& _return);
  void submit_ops_to_slave(SlaveOpsRetval& _return, const SlaveOps& ops);
  void send_submit_ops_to_slave(const SlaveOps& ops);
  void recv_submit_ops_to_slave(SlaveOpsRetval& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class SlaveManagerProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<SlaveManagerIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (SlaveManagerProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_ping(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_submit_ops_to_slave(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  SlaveManagerProcessor(boost::shared_ptr<SlaveManagerIf> iface) :
    iface_(iface) {
    processMap_["ping"] = &SlaveManagerProcessor::process_ping;
    processMap_["submit_ops_to_slave"] = &SlaveManagerProcessor::process_submit_ops_to_slave;
  }

  virtual ~SlaveManagerProcessor() {}
};

class SlaveManagerProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  SlaveManagerProcessorFactory(const ::boost::shared_ptr< SlaveManagerIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< SlaveManagerIfFactory > handlerFactory_;
};

class SlaveManagerMultiface : virtual public SlaveManagerIf {
 public:
  SlaveManagerMultiface(std::vector<boost::shared_ptr<SlaveManagerIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~SlaveManagerMultiface() {}
 protected:
  std::vector<boost::shared_ptr<SlaveManagerIf> > ifaces_;
  SlaveManagerMultiface() {}
  void add(boost::shared_ptr<SlaveManagerIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void ping(Ping_ACK& _return) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ping(_return);
    }
    ifaces_[i]->ping(_return);
    return;
  }

  void submit_ops_to_slave(SlaveOpsRetval& _return, const SlaveOps& ops) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->submit_ops_to_slave(_return, ops);
    }
    ifaces_[i]->submit_ops_to_slave(_return, ops);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class SlaveManagerConcurrentClient : virtual public SlaveManagerIf {
 public:
  SlaveManagerConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  SlaveManagerConcurrentClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void ping(Ping_ACK& _return);
  int32_t send_ping();
  void recv_ping(Ping_ACK& _return, const int32_t seqid);
  void submit_ops_to_slave(SlaveOpsRetval& _return, const SlaveOps& ops);
  int32_t send_submit_ops_to_slave(const SlaveOps& ops);
  void recv_submit_ops_to_slave(SlaveOpsRetval& _return, const int32_t seqid);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _WIN32
  #pragma warning( pop )
#endif



#endif
